### PR TITLE
Add Dockerfile and Gemfile

### PR DESCRIPTION
**Pull request by thatnerdjosh**

### CODE REVIEW

**Comment by sanjayankur31** [comment]
Is the dockerfile used in the GitHub actions workflow, or is this for us when running locally?

**Comment by thatnerdjosh** [comment]
For now it is just for local development; for the Gemfile, the GitHub actions could very easily be updated to use that, but for the Dockerfile, I'd need to look to see if GitHub actions uses container runners (and if so, where it sources the images)

**Comment by thatnerdjosh** [comment]
More than likely if it supported custom images, the image can hosted on GitHub container image registry

**Comment by sanjayankur31** [comment]
Cool, we can look into more advanced usage later. Merging this now. Thanks a bunch!

**Pull request merged**
